# 6. Analysis of longitudinal data

```{r}
date()
```

...

```{r}
RATSL <- read.csv("data/RATSL.csv", header=T, stringsAsFactors = F)
RATSL$ID <- as.factor(RATSL$ID)
RATSL$Group <- as.factor(RATSL$Group)

library(dplyr)
glimpse(RATSL)
```

...

```{r}
library(ggplot2)

ggplot(RATSL, aes(x = Time, y = Weight, linetype = ID)) +
  geom_line() +
  scale_linetype_manual(values = rep(1:10, times=4)) +
  facet_grid(. ~ Group, labeller = label_both) +
  theme(legend.position = "none") + 
  scale_y_continuous(limits = c(min(RATSL$Weight), max(RATSL$Weight)))
```

...

```{r}
# Standardise the variable Weight
RATSL <- RATSL %>%
  group_by(Time) %>%
  mutate(stdweight = (Weight - mean(Weight))/sd(Weight) ) %>%
  ungroup()
```

...

```{r}
# Plot again with the standardised Weight
ggplot(RATSL, aes(x = Time, y = stdweight, linetype = ID)) +
  geom_line() +
  scale_linetype_manual(values = rep(1:10, times=4)) +
  facet_grid(. ~ Group, labeller = label_both) +
  scale_y_continuous(name = "standardized weight")
```

...

```{r, message=FALSE}
# Number of weeks, baseline (week 0) included
n <- RATSL$Time %>% unique() %>% length()

# Summary data with mean and standard error of Weight by Group and Time 
RATSS <- RATSL %>%
  group_by(Group, Time) %>%
  summarise( mean = mean(Weight), se = sd(Weight)/sqrt(n) ) %>%
  ungroup()

# Plot the mean profiles
ggplot(RATSS, aes(x = Time, y = mean, linetype = Group, shape = Group)) +
  geom_line() +
  scale_linetype_manual(values = c(1,2,3)) +
  geom_point(size=3) +
  scale_shape_manual(values = c(1,2,3)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se, linetype="1"), width=0.3) +
  theme(legend.position = c(0.9,0.5)) +
  scale_y_continuous(name = "mean(Weight) +/- se(Weight)")
```

...

```{r, message=FALSE}
# Create a summary data by Group and ID with mean as the summary variable (ignoring baseline week 1).
RATSL64S <- RATSL %>%
  filter(Time > 1) %>%
  group_by(Group, ID) %>%
  summarise( mean=mean(Weight) ) %>%
  ungroup()

# Draw a boxplot of the mean versus treatment
ggplot(RATSL64S, aes(x = Group, y = mean)) +
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape=23, size=4, fill = "white") +
  scale_y_continuous(name = "mean(Weight), weeks 2-11")
```

...

```{r}
# Create a new data by filtering the outliers and adjust the ggplot code the draw the plot again with the new data
RATSL64S1 <- RATSL64S %>%
  filter(mean > 250, mean < 590, mean < 475 | mean > 500)

# Draw a new boxplot
ggplot(RATSL64S1, aes(x = Group, y = mean)) +
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape=23, size=4, fill = "white") +
  scale_y_continuous(name = "mean(Weight), weeks 2-11")
```

...

```{r}
# Cannot do two-sample t-test with three groups, so just doing analysis of variance on the linear model

# Add the baseline from the original data as a new variable to the summary data
RATS <- read.csv("data/RATS.csv", header=T, stringsAsFactors = F)

RATSL64S2 <- RATSL64S %>%
  mutate(baseline = RATS$WD1)

# Fit the linear model with the mean as the response 
fit <- lm(mean ~ baseline + Group, data = RATSL64S2)

# Compute the analysis of variance table for the fitted model with anova()
anova(fit)
```

...

```{r}
BPRSL <- read.csv("data/BPRSL.csv", header=T, stringsAsFactors = F)
BPRSL$treatment <- as.factor(BPRSL$treatment)
BPRSL$subject <- as.factor(BPRSL$subject)
```

...

```{r}
glimpse(BPRSL)
```

...


```{r}
treat1 <- BPRSL[BPRSL$treatment == 1,]
ggplot(treat1, aes(x = week, y = bprs, group = subject)) +
  geom_line(aes(color=subject)) +
  theme(legend.position = "top")
```

...

```{r}
treat2 <- BPRSL[BPRSL$treatment == 2,]
ggplot(treat2, aes(x = week, y = bprs, group = subject)) +
  geom_line(aes(color=subject)) +
  theme(legend.position = "top")
```

...

```{r}
# create a regression model RATS_reg
BPRS_reg <- lm(bprs ~ week + treatment, data = BPRSL)

# print out a summary of the model
summary(BPRS_reg)
```

...

```{r}
# access library lme4
library(lme4)

# Create a random intercept model
BPRS_ref <- lmer(bprs ~ week + treatment + (1 | subject), data = BPRSL, REML = FALSE)

# Print the summary of the model
summary(BPRS_ref)
```

...

```{r}
# create a random intercept and random slope model
BPRS_ref1 <- lmer(bprs ~ week + treatment + (week | subject), data = BPRSL, REML = FALSE)

# print a summary of the model
summary(BPRS_ref1)

# perform an ANOVA test on the two models
anova(BPRS_ref1, BPRS_ref)
```

...

```{r}
# create a random intercept and random slope model
BPRS_ref2 <- lmer(bprs ~ week * treatment + (week | subject), data = BPRSL, REML = FALSE)

# print a summary of the model
summary(BPRS_ref2)

# perform an ANOVA test on the two models
anova(BPRS_ref2, BPRS_ref1)
```

...

```{r}
# Create a vector of the fitted values
Fitted <- fitted(BPRS_ref2)

# Create a new column fitted to BPRSL
BPRSL <- BPRSL %>%
  mutate(Fitted)
```

...

```{r}
treat1 <- BPRSL[BPRSL$treatment == 1,]

# draw the plot of BPRSL
ggplot(treat1, aes(x = week, y = Fitted, group = subject)) +
  geom_line(aes(color = subject)) +
  scale_x_continuous(name = "weeks", breaks = seq(0, 8, 1)) +
  scale_y_continuous(name = "fitted bprs") +
  theme(legend.position = "top")
```

...

```{r}
treat2 <- BPRSL[BPRSL$treatment == 2,]

# draw the plot of BPRSL
ggplot(treat2, aes(x = week, y = Fitted, group = subject)) +
  geom_line(aes(color = subject)) +
  scale_x_continuous(name = "weeks", breaks = seq(0, 8, 1)) +
  scale_y_continuous(name = "fitted bprs") +
  theme(legend.position = "top")
```

...

